{% set name = "moreutils" %}
{% set version = "0.70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.joeyh.name/index.cgi/moreutils.git/snapshot/moreutils-{{ version }}.tar.gz
  sha256: 2170c46219ce8d6f17702321534769dfbfece52148a78cd12ea73b5d3a72ff7c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make

  run:
    - perl

test:
  commands:
    - echo "foo" | ts
    - sponge -h  # [build_platform == target_platform]

about:
  home: https://joeyh.name/code/moreutils/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Collection of additional unix tools.
  description: |
    moreutils is a growing collection of the unix tools that nobody thought to
    write long ago when unix was young.
  dev_url: https://git.joeyh.name/index.cgi/moreutils.git/

extra:
  recipe-maintainers:
    - matthiasdiener
    - notestaff
    - seowalex
