{% set name = "moreutils" %}
{% set version = "0.67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://deb.debian.org/debian/pool/main/m/{{ name }}/{{ name }}_{{ version }}.orig.tar.gz
  sha256: 03872f42c22943b21c62f711b693c422a4b8df9d1b8b2872ef9a34bd5d13ad10

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

  run:
    - perl
    - perl-ipc-run

test:
  commands:
    - combine -h
    - chronic echo "Hello world"
    - errno -h
    - isutf8 -i recipe/meta.yaml
    - lckdo echo.lock echo "Solo execution via lock file"
    - mispipe 'echo "Success"' 'grep Error'
    - sponge -h  # [build_platform == target_platform]
    - echo "Hello world time stamped" | ts
    - zrun -h

about:
  home: https://joeyh.name/code/moreutils/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Collection of additional unix tools.
  description: |
    moreutils is a growing collection of the unix tools that nobody thought to
    write long ago when unix was young.
  dev_url: https://git.joeyh.name/index.cgi/moreutils.git/

extra:
  recipe-maintainers:
    - matthiasdiener
    - notestaff
